[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Posts"
pageRef = "posts"
weight = 2

[[main]]
name = "Notes"
pageRef = "notes"
weight = 30

[[main]]
name = "Servers"
parent = "Notes"
pageRef = "servers"
weight = 30

[[main]]
name = "About"
pageRef = "about"
weight = 40

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20
