[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Posts"
pageRef = "posts"
weight = 2

[[main]]
name = "About"
pageRef = "about"
weight = 3

[[main]]
pre = "gitlab"
url = "https://git.kaleyfischer.xyz/DRAGONTOS/Website"
weight = 4

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

